-- Tabela de agendamentos da página /agenda
-- Rodar uma única vez no Supabase: Dashboard > SQL Editor > New query > colar e executar.

create table if not exists public.agendamentos (
  id           bigint generated by default as identity primary key,
  conta_id     bigint not null references public.contas(id) on delete cascade,
  nome_cliente text   not null,
  data         date   not null,
  horario      time   not null,
  created_at   timestamptz not null default now()
);

create index if not exists agendamentos_conta_data_horario_idx
  on public.agendamentos (conta_id, data, horario);

-- O app acessa o banco com a chave pública (anon), como nas tabelas
-- contas, transacoes, comandas etc. Se o seu projeto ativa RLS automaticamente
-- em tabelas novas, deixe esta tabela com a mesma configuração das demais.
-- Para manter o mesmo comportamento das outras tabelas sem RLS, descomente:
-- alter table public.agendamentos disable row level security;
